### PR TITLE
238 link share

### LINKED ISSUE #238: Link share icon or just have Twitter and Facebook?
Ask Hugh.

### PR DESCRIPTION
**Pull request by lschatzkin**
closes #238 
Adding link share icon to footer, removing google+ everywhere, rearranging footer per @hughillustration

### CODE REVIEW

**Comment by vbrown608** [comment]
When I click the copy link icon in chrome, the page grows to include the text field below, but the only visible difference is that scroll bar grows a bit, so it took me a minute to find the change. Do you think we could open the new field to the right of the link icon so that it's immediately visible?

(I'm not sure how to post a screenshot of this but I can show you if it doesn't make sense.)

**Comment by lschatzkin** [comment]
Good catch, and good suggestion!

**Comment by vbrown608** [comment]
Thanks for checking in about this! Here's the screenshot from Chromium:
link-field

**Comment by lschatzkin** [comment]
@vbrown608 Ready for review!

**Comment by vbrown608** [comment]
\*chef's kiss\*

**Pull request merged**
