### PR TITLE
Remove local part of email from domain field

### PR DESCRIPTION
**Pull request by rubicae**
Remove everything up to and including the `@` symbol in the domain input box when it loses focus.  This should let users enter email addresses and have them converted to domain names, addressing #249

### CODE REVIEW

**Comment by sydneyli** [comment]
Thanks @rubicae! Generally LGTM. One small nit/question: why trim the domain name when the field loses focus rather than on submit?

**Comment by rubicae** [comment]
I considered three possibilities for when to trim the email down to just the domain:
- as the user was typing (onkeypress / onkeydown or similar)
- when losing focus
- on submit

I thought changing it as the user was typing would be too jarring, particularly if they're entering it by hand.  Doing it when the input loses focus would hopefully be less jarring and still give the opportunity for the user to see the change if they continue moving around the page (e.g. click elsewhere or tab to the next part of the form).  Having it do this in on submit entirely hides the process from the user so they have no way of seeing the change.

I'm not particularly attached to doing it this way or sure that this is the best way and would be happy to do something else if you think a different one of these or a totally different solution is better.

**Comment by m0namon** [comment]
OK! That makes sense to me. Last thing is, would you mind also updating this text:
https://github.com/EFForg/starttls-frontend/blob/87646c1ed57c2e8c0e6397616b5a3066a5532466/layouts/partials/no-mxs.html#L3

Now that this is done, we can probably remove the last two sentences in the message.

**Comment by rubicae** [comment]
I have now removed the no longer relevant text!

**Pull request merged**
